name: Build GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - id: get-time
        run: echo "::set-output name=time::$(date -Iseconds)"
      - name: yarn install and build
        run: |
          yarn install
          yarn run build
          ln -s index.html build/playground.html
          ln -s index.html build/contributors.html
          ln -s index.html build/sourcecast.html
        # the `ln`s above are a hack to make GitHub Pages route /playground
        # and /contributors etc to index, instead of 404-ing.
        env:
          REACT_APP_PLAYGROUND_ONLY: 'TRUE'
          REACT_APP_VERSION: ${{ format('{0}-{1}', github.sha, steps.get-time.outputs.time) }}
          REACT_APP_ENVIRONMENT: 'pages'
          REACT_APP_MODULE_BACKEND_URL: https://source-academy.github.io/modules
          SW_EXCLUDE_REGEXES: '["^/source", "^/sicp", "^/modules", "^/ev3-source"]'
          PUBLIC_URL: 'https://murcia-cs4215.github.io/frontend'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
