name: Run CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Run CI
        run: |
          set -euo pipefail
          export TZ=Asia/Singapore
          export NODE_OPTIONS=--max_old_space_size=8192
          export GENERATE_SOURCEMAP=false
          JOBS=$(nproc) yarn install --frozen-lockfile
          yarn run tsc
          yarn run format:ci
          yarn run eslint
          yarn run build
          yarn run test-coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
